services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${DOM} # Create an .env file in the same folder as the compose, define the DOM variable and add the ENTIRE address for vaultwarden ex: https://vault.example.com
    volumes:
      - ./vw-data/:/data/
    ports: # You'll probably have to enable https to be able to enter your vault, you can use the reverse proxy used in this repositry (npm) to do so 
      - 8000:80

    # You can use any network config you want here but in my case I use an external bridge network and an static IP
    networks:
      marinero:
        ipv4_address: 172.18.0.5

networks:
  marinero:
    external: true # This is necessary if you have your own docker netowrk created and don't want docker to create a new one
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
