services:
  portainer:
    container_name: portainer
    # Working correctly with version 2.33.5 lts, as support for docker 29 has been added
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      # Port used in my case: (Use an http port ex. 80 if you don't plan on using https)
      - 9443:9443
    # You can use any network config you want here but in my case I use an external bridge network and an static IP
    networks:
      marinero:
        ipv4_address: 172.18.0.4

networks:
  marinero:
    external: true # This is necessary if you have your own docker netowrk created and don't want docker to create a new one
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
